"""CME Globex Equity trading calendar (versioned EFFECTIVE calendar).

The runtime calendar is the MERGE of the reproducible baseline
config/data/cme_calendar.yaml (generated by scripts/generate_cme_calendar.py
from pandas_market_calendars — a baseline, not authoritative by itself) with
the attributable official-CME override file
config/data/cme_calendar_overrides.yaml, which wins on conflict. Both files
are part of the effective configuration hash; calendar_identity() exposes the
baseline/overrides/merged SHA-256 identities for artifact binding. Sessions
open 17:00 America/Chicago the prior day and close at the per-date close time
(16:00 CT normal; early closes for shortened sessions; Good Friday 08:15 CT
short sessions exist). Session dates are exchange trading days; Saturdays,
Sundays, and full holidays are not session dates.
"""

from __future__ import annotations

from datetime import date, time
from functools import lru_cache
from pathlib import Path

import yaml
from pydantic import BaseModel

from nqresearch.config import _repo_root

STATUS_NORMAL = "normal"
STATUS_SHORTENED = "shortened"
STATUS_HOLIDAY = "holiday"
STATUS_WEEKEND = "weekend"
STATUS_OUT_OF_RANGE = "out_of_range"


class TradingCalendar(BaseModel):
    meta: dict
    trading_day_close_normal_ct: str
    session_open_ct: str
    holidays: list[str]
    early_closes: dict[str, str]

    @property
    def range_start(self) -> date:
        return date.fromisoformat(self.meta["range_start"])

    @property
    def range_end(self) -> date:
        return date.fromisoformat(self.meta["range_end"])

    def session_status(self, d: date) -> str:
        if not (self.range_start <= d <= self.range_end):
            return STATUS_OUT_OF_RANGE
        if d.weekday() >= 5:
            return STATUS_WEEKEND
        iso = d.isoformat()
        if iso in self.holidays:
            return STATUS_HOLIDAY
        if iso in self.early_closes:
            return STATUS_SHORTENED
        return STATUS_NORMAL

    def is_trading_day(self, d: date) -> bool:
        return self.session_status(d) in (STATUS_NORMAL, STATUS_SHORTENED)

    def is_override(self, d: date) -> bool:
        """True if this date's schedule comes from an official-CME override."""
        return d.isoformat() in self.meta.get("override_dates", [])

    def close_time_ct(self, d: date) -> time | None:
        status = self.session_status(d)
        if status == STATUS_SHORTENED:
            hh, mm = self.early_closes[d.isoformat()].split(":")
            return time(int(hh), int(mm))
        if status == STATUS_NORMAL:
            hh, mm = self.trading_day_close_normal_ct.split(":")
            return time(int(hh), int(mm))
        return None

    def expected_rth_span_seconds(self, d: date, rth_start: time = time(8, 30),
                                  rth_end: time = time(15, 0)) -> int | None:
        """Expected RTH span for the session: 08:30 CT to min(close, rth_end)."""
        close = self.close_time_ct(d)
        if close is None:
            return None
        eff_end = min(close, rth_end)
        if eff_end <= rth_start:
            return 0
        return (eff_end.hour * 3600 + eff_end.minute * 60) - (
            rth_start.hour * 3600 + rth_start.minute * 60
        )

    def next_trading_day(self, d: date) -> date:
        from datetime import timedelta

        n = d + timedelta(days=1)
        while not self.is_trading_day(n):
            n += timedelta(days=1)
        return n

    def trading_days_strictly_between(self, a: date, b: date) -> int:
        from datetime import timedelta

        n = 0
        d = a + timedelta(days=1)
        while d < b:
            if self.is_trading_day(d):
                n += 1
            d += timedelta(days=1)
        return n


@lru_cache(maxsize=None)
def load_calendar(repo_root: Path | None = None) -> TradingCalendar:
    """Baseline snapshot merged with official-CME overrides.

    cme_calendar.yaml is the reproducible pandas_market_calendars baseline;
    cme_calendar_overrides.yaml carries attributable official-CME corrections
    (e.g. the 2025-01-09 National Day of Mourning 08:30 CT close) and wins on
    conflict. Override dates are queryable via is_override().
    """
    root = repo_root or _repo_root()
    path = root / "config" / "data" / "cme_calendar.yaml"
    if not path.is_file():
        raise FileNotFoundError(
            f"CME calendar snapshot missing: {path}; run "
            "scripts/generate_cme_calendar.py"
        )
    doc = yaml.safe_load(path.read_text(encoding="utf-8"))
    override_path = root / "config" / "data" / "cme_calendar_overrides.yaml"
    override_dates: list[str] = []
    if override_path.is_file():
        ov = yaml.safe_load(override_path.read_text(encoding="utf-8")) or {}
        early = ov.get("early_close_overrides") or {}
        doc["early_closes"] = {**doc.get("early_closes", {}), **early}
        holi = ov.get("holiday_overrides") or []
        doc["holidays"] = sorted(set(doc.get("holidays", [])) | set(holi))
        override_dates = sorted({*early, *holi})
        doc["meta"]["overrides"] = ov.get("meta", {})
    cal = TradingCalendar(**doc)
    cal.meta["override_dates"] = override_dates
    return cal


def calendar_identity(repo_root: Path | None = None) -> dict:
    """Deterministic identity of the EFFECTIVE calendar (baseline + official
    overrides): both file hashes plus one merged-content hash, for binding
    derived artifacts (blocks, partitions) to the exact calendar used."""
    import hashlib
    import json

    root = repo_root or _repo_root()
    base = root / "config" / "data" / "cme_calendar.yaml"
    ov = root / "config" / "data" / "cme_calendar_overrides.yaml"
    cal = load_calendar(root)
    merged = {
        "holidays": cal.holidays,
        "early_closes": cal.early_closes,
        "normal_close_ct": cal.trading_day_close_normal_ct,
        "session_open_ct": cal.session_open_ct,
    }
    return {
        "baseline_file_sha256": hashlib.sha256(base.read_bytes()).hexdigest(),
        "overrides_file_sha256": (
            hashlib.sha256(ov.read_bytes()).hexdigest() if ov.is_file() else None
        ),
        "effective_calendar_sha256": hashlib.sha256(
            json.dumps(merged, sort_keys=True).encode()
        ).hexdigest(),
    }


def clear_calendar_cache() -> None:
    load_calendar.cache_clear()
